name: ItemRestriction
main: terranetworkorg.ItemRestriction.ItemRestriction
version: 1.0.0
author: TerraNetworkOrg
dev-url: http://dev.bukkit.org/server-mods/tno-itemrestriction/
depend: [Spout,Vault]
commands:
  itemrestriction:
    description: Lists plugin details
    usage: /<command>
    aliases: [ir,restrict]