name: ItemRestriction
main: terranetworkorg.ItemRestriction.ItemRestriction
version: 1.2.0
author: TerraNetworkOrg
depend: [Spout,Vault]
commands:
  itemrestriction:
    description: Lists plugin details
    usage: /<command>
    aliases: [ir,restrict]